title: Shane O. Chandler Seasoned IT Professional 
description: Over 15 years of experience in IT, currently transitioning to a career in Cyber Security.<span id="cursor">_</span>
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker 




